# Acordeón: Cheatsheet de Pandas

Manual de consulta rápida para trabajar con un `DataFrame`. 

**Archivo:** `base_generica_pandas.csv`, guardado en la misma carpeta que esta nota.

## 1. Importar Pandas

`import pandas as pd` importa la librería y le asigna el alias  `pd`.

In [1]:
import pandas as pd

**Resultado:** Pandas queda disponible como `pd` para trabajar con nuestra base.

## 2. Cargar una base de datos

`pd.read_csv("archivo.csv")` lee un CSV. Guardamos el resultado en la variable `df` para reutilizarlo.

In [2]:
df = pd.read_csv("base_generica_pandas.csv", encoding="utf-8")
df.head()

     col1  col2  col3  col4 col5   col6   col7  col8 col9  col10
0  380.79    49  56.4     1    B    Sur  0.294     5   No   Alto
1  951.21    56  13.0     9    A  Oeste  0.996     2   Sí  Medio
2  734.67    49  57.2     2    C  Norte  0.697     5   Sí   Alto
3  602.67    21  63.9     0    A  Norte  0.384     3   Sí   Alto
4  164.46    47  37.4     7    D    Sur  0.737     3   Sí  Medio

**Resultado:** `df` contiene los 100 registros y las 10 columnas del CSV; se muestran las primeras cinco filas. El índice de la izquierda identifica las filas y no es una columna del archivo.

## 3. Conocer nuestro DataFrame

Estos métodos y atributos permiten revisar la estructura antes de analizar los datos.

### Primeras y últimas filas

`head()` muestra las primeras cinco filas y `tail()` las últimas cinco. Podemos indicar otra cantidad con `head(n)` o `tail(n)`.

In [3]:
display(df.head())
display(df.tail(8))

     col1  col2  col3  col4 col5   col6   col7  col8 col9  col10
0  380.79    49  56.4     1    B    Sur  0.294     5   No   Alto
1  951.21    56  13.0     9    A  Oeste  0.996     2   Sí  Medio
2  734.67    49  57.2     2    C  Norte  0.697     5   Sí   Alto
3  602.67    21  63.9     0    A  Norte  0.384     3   Sí   Alto
4  164.46    47  37.4     7    D    Sur  0.737     3   Sí  Medio

      col1  col2  col3  col4 col5   col6   col7  col8 col9 col10
92  763.18    37  64.5     9    A   Este  0.524     1   No  Bajo
93  565.66    53  42.3     1    C  Oeste  0.698     5   Sí  Alto
94  773.26    36  68.2     2    C  Norte  0.796     4   Sí  Alto
95  498.86    43  47.7     8    B    Sur  0.459     2   Sí  Bajo
96  527.51    20  44.4     6    C   Este  0.842     2   Sí  Alto
97  433.27    36  30.6     3    D  Norte  0.769     3   Sí  Bajo
98   35.16    37  38.5     9    A  Norte  0.066     3   Sí  Bajo
99  116.81    49  56.3     4    B    Sur  0.046     5   Sí  Bajo

**Resultado:** la primera tabla muestra las filas con índices del 0 al 4; la segunda, las ocho últimas, con índices del 92 al 99.

### Dimensiones y nombres

`shape` y `columns` son atributos: se escriben **sin paréntesis**. `shape` devuelve `(filas, columnas)`.

In [4]:
print("Dimensiones:", df.shape)
print("Columnas:", df.columns.tolist())

Dimensiones: (100, 10)
Columnas: ['col1', 'col2', 'col3', 'col4', 'col5', 'col6', 'col7', 'col8', 'col9', 'col10']

**Resultado:** `(100, 10)` indica 100 filas y 10 columnas. La lista contiene los nombres desde `col1` hasta `col10`.

### Información general

`info()` imprime los nombres de las columnas, la cantidad de valores **no nulos**, y los tipos de datos

In [5]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 10 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   col1    100 non-null    float64
 1   col2    100 non-null    int64
 2   col3    100 non-null    float64
 3   col4    100 non-null    int64
 4   col5    100 non-null    str
 5   col6    100 non-null    str
 6   col7    100 non-null    float64
 7   col8    100 non-null    int64
 8   col9    100 non-null    str
 9   col10   100 non-null    str
dtypes: float64(3), int64(3), str(4)
memory usage: 7.9 KB

**Resultado:** cada columna tiene 100 valores no nulos; no hay datos faltantes. Se distinguen columnas numéricas y de texto.

## 4. Seleccionar columnas

Escribimos el nombre de cada columna entre comillas. Un nombre selecciona una `Series`; una lista de nombres selecciona un `DataFrame`.

### Una columna

Sintaxis: `df["columna"]`. Usamos `head()` para mantener breve la vista del ejemplo.

In [6]:
df["col5"].head()

0    B
1    A
2    C
3    A
4    D
Name: col5, dtype: str

**Resultado:** una `Series` con las primeras cinco categorías de `col5`. Sin `head()`, la selección incluye los 100 registros.

### Varias columnas

Sintaxis: `df[["columna1", "columna2"]]`. El corchete interior crea una lista.

In [7]:
df[["col8", "col7"]].head()

   col8   col7
0     5  0.294
1     2  0.996
2     5  0.697
3     3  0.384
4     3  0.737

**Resultado:** un `DataFrame` con las primeras cinco filas de `col8` y `col7`, en ese orden.

### Selección mediante listas

Podemos guardar los nombres en una lista y pasarla a `df[...]`.

In [8]:
columnas_seleccionadas = ["col1", "col10", "col6", "col8"]
df[columnas_seleccionadas].head()

     col1  col10   col6  col8
0  380.79   Alto    Sur     5
1  951.21  Medio  Oeste     2
2  734.67   Alto  Norte     5
3  602.67   Alto  Norte     3
4  164.46  Medio    Sur     3

**Resultado:** una tabla con las cuatro columnas solicitadas y una vista de cinco filas.

## 5. Filtrar datos

Una comparación como `df["col6"] == "Sur"` produce valores `True` y `False`. `df[condicion]` conserva solo las filas donde la condición es verdadera.

### Condición numérica

Usamos operadores como `>`,  `>=`,  y  `!=`.

In [9]:
df[df["col1"] > 500]

      col1  col2  col3  col4 col5   col6   col7  col8 col9  col10
1   951.21    56  13.0     9    A  Oeste  0.996     2   Sí  Medio
2   734.67    49  57.2     2    C  Norte  0.697     5   Sí   Alto
3   602.67    21  63.9     0    A  Norte  0.384     3   Sí   Alto
7   867.51    56  55.9     6    A  Norte  0.058     1   No   Bajo
8   605.10    62  40.6     9    A  Oeste  0.395     3   No  Medio
9   710.99    32  42.2     4    A    Sur  0.107     4   Sí  Medio
11  970.21    46  55.7     4    B    Sur  0.170     1   No   Bajo
12  834.12    53  50.9     6    A   Este  0.647     3   No   Alto
17  529.51    45  34.0     9    A  Norte  0.260     5   Sí   Bajo
20  615.73    62  63.8     5    D  Oeste  0.280     3   Sí   Alto
25  787.32    61  67.5     6    D  Oeste  0.076     2   No   Alto
27  519.09    47  33.6     5    B   Este  0.417     5   No   Bajo
28  596.49    28   6.8     6    D   Este  0.581     1   No   Bajo
30  611.47    42  49.9     9    D  Norte  0.083     1   No   Alto
33  949.40    18  33.3     5    A    Sur  0.165     2   No  Medio
34  965.98    44  63.0     8    C  Oeste  0.411     1   Sí   Bajo
35  810.31    30  64.4     4    A   Este  0.778     2   No   Bajo
38  687.39    56  84.1     4    B  Oeste  0.377     1   No  Medio
41  500.23    44  27.5     4    B   Este  0.829     1   No   Alto
43  910.23    54  56.2     3    D    Sur  0.064     5   Sí  Medio
45  665.90    59  63.1     4    B   Este  0.134     2   Sí   Alto
47  524.87    41  29.8     9    C   Este  0.075     1   Sí   Alto
48  551.24    32  62.8     9    C  Norte  0.692     1   Sí   Bajo
50  969.89    49  49.9     4    D    Sur  0.750     5   No   Bajo
51  777.38    41  26.4     3    D  Oeste  0.913     4   Sí   Bajo
52  940.10    58  72.2     1    A    Sur  0.585     2   Sí   Alto
53  895.88    29  56.0     3    A    Sur  0.726     4   No   Alto
54  601.92    56  23.3     9    C  Oeste  0.757     2   Sí  Medio
55  922.66    19  46.4     9    D  Oeste  0.378     5   No  Medio
62  830.45    40  35.8     7    D   Este  0.757     5   No   Alto
65  547.27    50  23.8     0    C    Sur  0.022     3   Sí  Medio
67  804.18    36  25.7     3    A   Este  0.476     1   No   Alto
69  987.02    61  70.8     1    C  Norte  0.308     4   No   Bajo
70  774.52    43  37.2     2    D  Norte  0.816     2   No  Medio
73  817.31    49  43.3     2    C    Sur  0.792     2   Sí   Bajo
74  709.79    21  56.3    10    A  Norte  0.590     4   Sí  Medio
75  731.72    28  39.1     4    D    Sur  0.480     1   No   Bajo
76  773.56    34  23.0     2    A    Sur  0.421     1   Sí   Bajo
80  864.47    51  39.0     9    C  Norte  0.903     4   No   Alto
81  627.07    23  52.9    10    A  Norte  0.617     2   No   Bajo
86  732.31    50  32.0     6    B  Norte  0.091     4   No   Bajo
87  641.18    26  68.0     0    C   Este  0.726     2   No   Alto
88  888.34    23  52.2     9    B  Oeste  0.547     1   No  Medio
91  716.11    20  21.8     9    C   Este  0.298     2   No  Medio
92  763.18    37  64.5     9    A   Este  0.524     1   No   Bajo
93  565.66    53  42.3     1    C  Oeste  0.698     5   Sí   Alto
94  773.26    36  68.2     2    C  Norte  0.796     4   Sí   Alto
96  527.51    20  44.4     6    C   Este  0.842     2   Sí   Alto

**Resultado:** solo los registros cuyo valor de `col1` es mayor que 500; el valor 500 queda excluido.

### Condición categórica

Para comparar texto, escribimos el valor entre comillas. `==` compara; `=` asigna.

In [10]:
df[df["col6"] == "Sur"]

      col1  col2  col3  col4 col5 col6   col7  col8 col9  col10
0   380.79    49  56.4     1    B  Sur  0.294     5   No   Alto
4   164.46    47  37.4     7    D  Sur  0.737     3   Sí  Medio
6    67.50    40  78.1     9    A  Sur  0.959     3   Sí   Bajo
9   710.99    32  42.2     4    A  Sur  0.107     4   Sí  Medio
11  970.21    46  55.7     4    B  Sur  0.170     1   No   Bajo
13  220.22    30  57.5     8    A  Sur  0.388     3   Sí   Bajo
14  190.01    49  47.8     4    D  Sur  0.229     3   No  Medio
18  437.63    19  51.6     0    C  Sur  0.453     2   No  Medio
24  461.51    61  22.3     0    D  Sur  0.133     4   Sí  Medio
33  949.40    18  33.3     5    A  Sur  0.165     2   No  Medio
39  445.75    23  52.2     9    A  Sur  0.750     2   Sí   Alto
42   44.04    26  49.8     6    D  Sur  0.569     3   No   Bajo
43  910.23    54  56.2     3    D  Sur  0.064     5   Sí  Medio
46  318.59    61  69.5     6    A  Sur  0.014     4   No   Alto
50  969.89    49  49.9     4    D  Sur  0.750     5   No   Bajo
52  940.10    58  72.2     1    A  Sur  0.585     2   Sí   Alto
53  895.88    29  56.0     3    A  Sur  0.726     4   No   Alto
65  547.27    50  23.8     0    C  Sur  0.022     3   Sí  Medio
73  817.31    49  43.3     2    C  Sur  0.792     2   Sí   Bajo
75  731.72    28  39.1     4    D  Sur  0.480     1   No   Bajo
76  773.56    34  23.0     2    A  Sur  0.421     1   Sí   Bajo
85  331.93    33  80.0     2    C  Sur  0.555     2   Sí  Medio
95  498.86    43  47.7     8    B  Sur  0.459     2   Sí   Bajo
99  116.81    49  56.3     4    B  Sur  0.046     5   Sí   Bajo

**Resultado:** los 24 registros de la categoría `Sur` en `col6`.

### Varias condiciones: 

Encerramos cada comparación entre paréntesis y usamos `&` para exigir que ambas se cumplan.

In [11]:
df[(df["col6"] == "Sur") & (df["col5"] != "B")]

      col1  col2  col3  col4 col5 col6   col7  col8 col9  col10
4   164.46    47  37.4     7    D  Sur  0.737     3   Sí  Medio
6    67.50    40  78.1     9    A  Sur  0.959     3   Sí   Bajo
9   710.99    32  42.2     4    A  Sur  0.107     4   Sí  Medio
13  220.22    30  57.5     8    A  Sur  0.388     3   Sí   Bajo
14  190.01    49  47.8     4    D  Sur  0.229     3   No  Medio
18  437.63    19  51.6     0    C  Sur  0.453     2   No  Medio
24  461.51    61  22.3     0    D  Sur  0.133     4   Sí  Medio
33  949.40    18  33.3     5    A  Sur  0.165     2   No  Medio
39  445.75    23  52.2     9    A  Sur  0.750     2   Sí   Alto
42   44.04    26  49.8     6    D  Sur  0.569     3   No   Bajo
43  910.23    54  56.2     3    D  Sur  0.064     5   Sí  Medio
46  318.59    61  69.5     6    A  Sur  0.014     4   No   Alto
50  969.89    49  49.9     4    D  Sur  0.750     5   No   Bajo
52  940.10    58  72.2     1    A  Sur  0.585     2   Sí   Alto
53  895.88    29  56.0     3    A  Sur  0.726     4   No   Alto
65  547.27    50  23.8     0    C  Sur  0.022     3   Sí  Medio
73  817.31    49  43.3     2    C  Sur  0.792     2   Sí   Bajo
75  731.72    28  39.1     4    D  Sur  0.480     1   No   Bajo
76  773.56    34  23.0     2    A  Sur  0.421     1   Sí   Bajo
85  331.93    33  80.0     2    C  Sur  0.555     2   Sí  Medio

**Resultado:** filas de `Sur` cuya categoría en `col5` es diferente de `B`.

### Varias condiciones: O y negación

Usamos `|` para que se cumpla al menos una condición y `~` para negar una máscara. Para combinar Series usamos `&` y `|`

In [12]:
display(df[(df["col5"] == "A") | (df["col6"] == "Norte")])
display(df[~(df["col6"] == "Sur")].head())

      col1  col2  col3  col4 col5   col6   col7  col8 col9  col10
1   951.21    56  13.0     9    A  Oeste  0.996     2   Sí  Medio
2   734.67    49  57.2     2    C  Norte  0.697     5   Sí   Alto
3   602.67    21  63.9     0    A  Norte  0.384     3   Sí   Alto
6    67.50    40  78.1     9    A    Sur  0.959     3   Sí   Bajo
7   867.51    56  55.9     6    A  Norte  0.058     1   No   Bajo
8   605.10    62  40.6     9    A  Oeste  0.395     3   No  Medio
9   710.99    32  42.2     4    A    Sur  0.107     4   Sí  Medio
10   30.38    60  50.2     9    D  Norte  0.336     4   No  Medio
12  834.12    53  50.9     6    A   Este  0.647     3   No   Alto
13  220.22    30  57.5     8    A    Sur  0.388     3   Sí   Bajo
15  191.57    24  52.7     0    D  Norte  0.266     5   No   Alto
16  311.20    39  64.5     9    C  Norte  0.360     2   No   Alto
17  529.51    45  34.0     9    A  Norte  0.260     5   Sí   Bajo
22  299.22    45  59.8     7    A  Norte  0.603     5   Sí   Bajo
23  372.70    45  66.5     4    C  Norte  0.271     2   Sí  Medio
26  207.68    37  35.2     4    C  Norte  0.941     5   Sí   Bajo
29   55.99    45  38.0     2    A  Norte  0.919     5   Sí   Alto
30  611.47    42  49.9     9    D  Norte  0.083     1   No   Alto
31  178.82    56  44.3     2    A  Oeste  0.877     4   No  Medio
33  949.40    18  33.3     5    A    Sur  0.165     2   No  Medio
35  810.31    30  64.4     4    A   Este  0.778     2   No   Bajo
37  106.70    20  21.7     3    A  Norte  0.985     3   No   Bajo
39  445.75    23  52.2     9    A    Sur  0.750     2   Sí   Alto
40  130.82    25  58.1     9    A   Este  0.393     1   No  Medio
44  266.19    50  47.9     0    A   Este  0.037     1   No   Bajo
46  318.59    61  69.5     6    A    Sur  0.014     4   No   Alto
48  551.24    32  62.8     9    C  Norte  0.692     1   Sí   Bajo
49  193.01    49  55.9     5    A  Norte  0.534     3   No   Bajo
52  940.10    58  72.2     1    A    Sur  0.585     2   Sí   Alto
53  895.88    29  56.0     3    A    Sur  0.726     4   No   Alto
56   97.61    20  54.9     2    A  Oeste  0.241     2   No   Bajo
57  204.02    54  57.6     9    C  Norte  0.205     3   No   Alto
59  332.08    19  55.1     7    B  Norte  0.275     3   Sí   Alto
61  278.64    45  73.2     3    D  Norte  0.878     4   Sí  Medio
63  363.19    54  41.0     6    C  Norte  0.047     2   Sí   Alto
66  149.51    18  29.9    10    D  Norte  0.498     3   Sí   Alto
67  804.18    36  25.7     3    A   Este  0.476     1   No   Alto
68   83.81    19  32.8     7    A  Oeste  0.831     5   No   Bajo
69  987.02    61  70.8     1    C  Norte  0.308     4   No   Bajo
70  774.52    43  37.2     2    D  Norte  0.816     2   No  Medio
71  206.73    49  34.6     0    A  Oeste  0.968     1   Sí   Alto
72   15.47    23  63.2     0    D  Norte  0.088     1   No   Alto
74  709.79    21  56.3    10    A  Norte  0.590     4   Sí  Medio
76  773.56    34  23.0     2    A    Sur  0.421     1   Sí   Bajo
78  364.88    41  26.7     0    D  Norte  0.639     4   Sí   Bajo
79  124.71    22  42.3     7    A  Oeste  0.805     1   Sí   Alto
80  864.47    51  39.0     9    C  Norte  0.903     4   No   Alto
81  627.07    23  52.9    10    A  Norte  0.617     2   No   Bajo
82  337.59    39  41.7     1    A   Este  0.980     3   No  Medio
83   72.92    28  48.1     2    B  Norte  0.608     1   No  Medio
86  732.31    50  32.0     6    B  Norte  0.091     4   No   Bajo
89  477.49    33  52.1     7    A  Norte  0.451     4   Sí   Bajo
92  763.18    37  64.5     9    A   Este  0.524     1   No   Bajo
94  773.26    36  68.2     2    C  Norte  0.796     4   Sí   Alto
97  433.27    36  30.6     3    D  Norte  0.769     3   Sí   Bajo
98   35.16    37  38.5     9    A  Norte  0.066     3   Sí   Bajo

     col1  col2  col3  col4 col5   col6   col7  col8 col9  col10
1  951.21    56  13.0     9    A  Oeste  0.996     2   Sí  Medio
2  734.67    49  57.2     2    C  Norte  0.697     5   Sí   Alto
3  602.67    21  63.9     0    A  Norte  0.384     3   Sí   Alto
5  164.43    54  60.2     2    D   Este  0.915     3   No   Alto
7  867.51    56  55.9     6    A  Norte  0.058     1   No   Bajo

**Resultado:** la primera tabla incluye filas con `col5` igual a `A`, con región `Norte` o con ambas condiciones. La segunda muestra cinco registros que no pertenecen a `Sur`.

## 6. Ordenar datos

`sort_values()` ordena por los valores de una o varias columnas. Por defecto, el orden es ascendente.

### Una columna

`ascending=False` cambia el orden a descendente.

In [13]:
display(df.sort_values("col1").head())
display(df.sort_values("col1", ascending=False).head())

     col1  col2  col3  col4 col5   col6   col7  col8 col9  col10
72  15.47    23  63.2     0    D  Norte  0.088     1   No   Alto
10  30.38    60  50.2     9    D  Norte  0.336     4   No  Medio
98  35.16    37  38.5     9    A  Norte  0.066     3   Sí   Bajo
42  44.04    26  49.8     6    D    Sur  0.569     3   No   Bajo
58  54.78    34  48.1     0    D   Este  0.251     3   No   Alto

      col1  col2  col3  col4 col5   col6   col7  col8 col9  col10
69  987.02    61  70.8     1    C  Norte  0.308     4   No   Bajo
11  970.21    46  55.7     4    B    Sur  0.170     1   No   Bajo
50  969.89    49  49.9     4    D    Sur  0.750     5   No   Bajo
34  965.98    44  63.0     8    C  Oeste  0.411     1   Sí   Bajo
1   951.21    56  13.0     9    A  Oeste  0.996     2   Sí  Medio

**Resultado:** se muestran los cinco valores más pequeños de `col1` y luego los cinco más grandes, junto con sus demás columnas.

### Varias columnas

Pasamos listas a `by` y a `ascending`: cada dirección corresponde a una columna.

In [14]:
df.sort_values(by=["col6", "col1"], ascending=[True, False]).head(10)

      col1  col2  col3  col4 col5  col6   col7  col8 col9  col10
12  834.12    53  50.9     6    A  Este  0.647     3   No   Alto
62  830.45    40  35.8     7    D  Este  0.757     5   No   Alto
35  810.31    30  64.4     4    A  Este  0.778     2   No   Bajo
67  804.18    36  25.7     3    A  Este  0.476     1   No   Alto
92  763.18    37  64.5     9    A  Este  0.524     1   No   Bajo
91  716.11    20  21.8     9    C  Este  0.298     2   No  Medio
45  665.90    59  63.1     4    B  Este  0.134     2   Sí   Alto
87  641.18    26  68.0     0    C  Este  0.726     2   No   Alto
28  596.49    28   6.8     6    D  Este  0.581     1   No   Bajo
96  527.51    20  44.4     6    C  Este  0.842     2   Sí   Alto

**Resultado:** filas ordenadas alfabéticamente por `col6` y, dentro de cada región, por `col1` de mayor a menor. El índice original se conserva.

## 7. Estadística descriptiva

Estas operaciones resumen los valores numéricos. Normalmente omiten los valores faltantes

### Resumen general

`describe()` calcula conteo, media, desviación estándar, mínimo, cuartiles y máximo de las columnas numéricas.

In [15]:
df.describe()

             col1        col2        col3       col4        col7        col8
count  100.000000  100.000000  100.000000  100.00000  100.000000  100.000000
mean   475.479300   40.650000   48.323000    4.72000    0.493950    2.900000
std    294.514525   13.699056   15.726294    3.26314    0.291855    1.396243
min     15.470000   18.000000    6.800000    0.00000    0.014000    1.000000
25%    201.267500   28.000000   37.350000    2.00000    0.264500    2.000000
50%    469.500000   43.000000   49.900000    4.00000    0.480000    3.000000
75%    732.900000   50.250000   57.525000    8.00000    0.751750    4.000000
max    987.020000   65.000000   84.100000   10.00000    0.996000    5.000000

**Resultado:** una tabla con ocho estadísticas por columna numérica. `50%` es la mediana; `25%` y `75%` son los otros cuartiles.

### Estadísticas de una columna

`mean()` calcula la media; `median()`, la mediana; `min()` y `max()`, los extremos; `std()`, la desviación estándar muestral (por defecto, `ddof=1`).

In [16]:
print("Media:", df["col1"].mean())
print("Mediana:", df["col1"].median())
print("Mínimo:", df["col1"].min())
print("Máximo:", df["col1"].max())
print("Desviación estándar:", df["col1"].std())

Media: 475.4793000000001
Mediana: 469.5
Mínimo: 15.47
Máximo: 987.02
Desviación estándar: 294.5145254165289

**Resultado:** para `col1`, la media es aproximadamente 475.48, la mediana 469.50, el mínimo 15.47, el máximo 987.02 y la desviación estándar 294.51.

## 8. Trabajar con variables categóricas

Podemos consultar qué categorías existen y cuántas veces aparecen, sin realizar operaciones aritméticas con ellas.

### Frecuencias

`value_counts()` cuenta los registros de cada categoría y ordena por frecuencia descendente.

In [17]:
df["col6"].value_counts()

col6
Norte    33
Sur      24
Oeste    22
Este     21
Name: count, dtype: int64

**Resultado:** `Norte` aparece 33 veces; `Sur`, 24; `Oeste`, 22; y `Este`, 21. Por defecto, los nulos se excluyen; `dropna=False` permite incluirlos.

### Categorías distintas

`unique()` devuelve los valores distintos en orden de aparición; `nunique()` devuelve cuántos hay, excluyendo nulos por defecto.

In [18]:
print("Categorías:", df["col6"].unique())
print("Número de categorías:", df["col6"].nunique())

Categorías: <StringArray>
['Sur', 'Oeste', 'Norte', 'Este']
Length: 4, dtype: str
Número de categorías: 4

**Resultado:** los valores distintos son `Sur`, `Oeste`, `Norte` y `Este`

## 9. Agrupar datos

`groupby()` separa los registros por categorías para calcular estadísticas dentro de cada grupo. Después de agrupar elegimos una operación como `mean()`, `size()` o `agg()`.

### Promedio por categoría

Seleccionamos `col1` después de agrupar por `col10` y calculamos su media.

In [19]:
df.groupby("col10")["col1"].mean()

col10
Alto     480.194412
Bajo     473.109722
Medio    472.979000
Name: col1, dtype: float64

**Resultado:** una media de `col1` para cada categoría de `col10`: `Alto`, `Bajo` y `Medio`.

### Conteos por categoría

`size()` cuenta filas, mientras que `count()` cuenta valores no nulos de cada columna seleccionada. También podemos agrupar por más de una columna.

In [20]:
display(df.groupby("col6").size())
display(df.groupby(["col10", "col5"])[["col1", "col3"]].count())

col6
Este     21
Norte    33
Oeste    22
Sur      24
dtype: int64

            col1  col3
col10 col5
Alto  A       10    10
      B        5     5
      C       10    10
      D        9     9
Bajo  A       16    16
      B        6     6
      C        6     6
      D        8     8
Medio A        8     8
      B        4     4
      C       10    10
      D        8     8

**Resultado:** la primera salida cuenta registros por región. La segunda cuenta valores no nulos de `col1` y `col3` por combinación de `col10` y `col5`; ambos conteos coinciden porque no hay nulos.

### Varias agregaciones

`agg()` permite calcular varias estadísticas en una sola operación. Cada par indica la columna de origen y la función.

In [21]:
resumen = df.groupby("col6").agg(
    registros=("col1", "size"),
    promedio_col1=("col1", "mean"),
    minimo_col1=("col1", "min"),
    maximo_col1=("col1", "max")
)
resumen

       registros  promedio_col1  minimo_col1  maximo_col1
col6
Este          21     509.148095        54.78       834.12
Norte         33     420.017879        15.47       987.02
Oeste         22     459.116818        74.40       965.98
Sur           24     537.277500        44.04       970.21

**Resultado:** una tabla de cuatro filas, una por región, con el número de registros y tres estadísticas de `col1`.

## 10. Crear y modificar columnas

`df["nueva_columna"] = expresion` crea una columna; si el nombre ya existe, reemplaza sus valores. Las operaciones entre columnas se realizan fila por fila. Usaremos `df_editado = df.copy()` para practicar y poder repetir la sección desde la base original.

### Crear columnas

Creamos una columna numérica y otra lógica a partir de `col1`.

In [22]:
df_editado = df.copy()
df_editado["col1_doble"] = df_editado["col1"] * 2
df_editado["supera_500"] = df_editado["col1"] > 500
df_editado[["col1", "col1_doble", "supera_500"]].head()

     col1  col1_doble  supera_500
0  380.79      761.58       False
1  951.21     1902.42        True
2  734.67     1469.34        True
3  602.67     1205.34        True
4  164.46      328.92       False

**Resultado:** dos nuevas columnas: el doble de `col1` y un indicador `True` o `False` que señala si supera 500.

### Modificar una columna y asignar con condición

Podemos reemplazar una columna completa o usar `.loc[condicion, "columna"]` para modificar solo algunas filas.

In [23]:
df_editado["col1_doble"] = df_editado["col1_doble"].round(1)
df_editado.loc[df_editado["col6"] == "Sur", "col9"] = "Sí"
df_editado.loc[df_editado["col6"] == "Sur", ["col6", "col9", "col1_doble"]].head()

   col6 col9  col1_doble
0   Sur   Sí       761.6
4   Sur   Sí       328.9
6   Sur   Sí       135.0
9   Sur   Sí      1422.0
11  Sur   Sí      1940.4

**Resultado:** `col1_doble` queda redondeada a un decimal y `col9` vale `Sí` en todas las filas de `Sur` de la copia. La vista muestra cinco de esas filas. El `df` original conserva sus valores.