In [1]:
import pandas as pd 
df= pd.read_csv("https://raw.githubusercontent.com/vida092/diplomado_big_data/refs/heads/main/peliculas.csv")

# Ronda 1. Conociendo los datos

## Utiliza el Dataframe de peliculas proporcionado para responder las siguientes preguntas.

- ¿Cuántas películas hay en el dataset?
- ¿Cuántas variables o columnas contiene el dataset?
- ¿Cuáles son las columnas que contiene el DataFrame?
- ¿Qué tipo de dato tiene cada columna?
- ¿Existen valores faltantes en el dataset?
- ¿Cuánta información contiene cada columna?
- Observa especialmente los valores no nulos.
- ¿Qué columnas contienen información numérica?
- ¿Qué columnas contienen información categórica o textual?
- Obtén únicamente la columna que contiene el título de las películas.
- Obtén únicamente la columna que contiene el rating de las películas.
- Obtén únicamente las columnas correspondientes al título, género y rating.
- Obtén las estadísticas descriptivas de las variables numéricas.
- ¿Cuál es el rating promedio de las películas?
- ¿Cuál es la duración promedio de las películas?
- ¿Cuál es la película con mayor duración?
- ¿Cuál es la película con mayor rating?
- ¿Cuál es la película que recibió más votos?
- ¿Qué géneros aparecen en el dataset y cuántas películas hay de cada género?
- ¿Qué país aparece con mayor frecuencia?
- ¿Qué plataforma tiene más películas?

In [2]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 12 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   id                100 non-null    int64
 1   titulo            100 non-null    str
 2   fecha_estreno     100 non-null    str
 3   genero            100 non-null    str
 4   duracion_min      100 non-null    int64
 5   presupuesto_musd  100 non-null    float64
 6   taquilla_musd     100 non-null    float64
 7   popularidad       100 non-null    float64
 8   rating            100 non-null    float64
 9   votos             100 non-null    int64
 10  idioma_original   100 non-null    str
 11  adulto            100 non-null    bool
dtypes: bool(1), float64(4), int64(3), str(4)
memory usage: 8.8 KB

In [3]:
#Ejercicio 1 y 2

df.shape 
#100 peliculas, 12 variables(columnas)

(100, 12)

In [4]:
#Ejercicio 3
df.columns

Index(['id', 'titulo', 'fecha_estreno', 'genero', 'duracion_min',
       'presupuesto_musd', 'taquilla_musd', 'popularidad', 'rating', 'votos',
       'idioma_original', 'adulto'],
      dtype='str')

In [5]:
#Ejercicio 4
df.dtypes
#int64 = enteros, str = string, float64 = decimales, object = texto

id                    int64
titulo                  str
fecha_estreno           str
genero                  str
duracion_min          int64
presupuesto_musd    float64
taquilla_musd       float64
popularidad         float64
rating              float64
votos                 int64
idioma_original         str
adulto                 bool
dtype: object

In [6]:
#Ejercicio 5
df.isnull().sum()
#No hay NaN en ninguna columna

id                  0
titulo              0
fecha_estreno       0
genero              0
duracion_min        0
presupuesto_musd    0
taquilla_musd       0
popularidad         0
rating              0
votos               0
idioma_original     0
adulto              0
dtype: int64

In [7]:
#Ejercicio 6
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 12 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   id                100 non-null    int64
 1   titulo            100 non-null    str
 2   fecha_estreno     100 non-null    str
 3   genero            100 non-null    str
 4   duracion_min      100 non-null    int64
 5   presupuesto_musd  100 non-null    float64
 6   taquilla_musd     100 non-null    float64
 7   popularidad       100 non-null    float64
 8   rating            100 non-null    float64
 9   votos             100 non-null    int64
 10  idioma_original   100 non-null    str
 11  adulto            100 non-null    bool
dtypes: bool(1), float64(4), int64(3), str(4)
memory usage: 8.8 KB

In [8]:
#Ejercicio 7 y 8
df.select_dtypes(include="number").columns
df.select_dtypes(include="object").columns

C:\Users\Omen\AppData\Local\Temp\ipykernel_19476\3986729831.py:3: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  df.select_dtypes(include="object").columns

Index(['titulo', 'fecha_estreno', 'genero', 'idioma_original'], dtype='str')

In [9]:
#Ejercicio 9
df["titulo"]

0             100 Years
1       American Static
2             September
3           Light Years
4               Harvest
            ...
95      Batman: Parte 2
96              Золушка
97         Heart Eyes 2
98    Murder, She Wrote
99       Endless Summer
Name: titulo, Length: 100, dtype: str

In [10]:
#Ejercicio 10
df["rating"]

0     0.0
1     0.0
2     0.0
3     0.0
4     0.0
     ...
95    0.0
96    0.0
97    0.0
98    0.0
99    0.0
Name: rating, Length: 100, dtype: float64

In [11]:
#Ejercicio 11
df[["titulo", "genero", "rating"]]

               titulo           genero  rating
0           100 Years       Sin género     0.0
1     American Static  Ciencia ficción     0.0
2           September           Terror     0.0
3         Light Years       Sin género     0.0
4             Harvest           Terror     0.0
..                ...              ...     ...
95    Batman: Parte 2         Misterio     0.0
96            Золушка       Sin género     0.0
97       Heart Eyes 2           Terror     0.0
98  Murder, She Wrote         Misterio     0.0
99     Endless Summer            Drama     0.0

[100 rows x 3 columns]

In [12]:
#Ejercicio 12
df.describe()

,id,duracion_min,presupuesto_musd,taquilla_musd,popularidad,rating,votos
count,1.000000e+02,100.000000,100.0000,100.0,100.000000,100.0,100.0
mean,1.479390e+06,21.730000,8.1805,0.0,1.385000,0.0,0.0
std,3.080932e+05,50.850316,29.3839,0.0,2.069646,0.0,0.0
min,2.165270e+05,0.000000,0.0000,0.0,0.010000,0.0,0.0
25%,1.363082e+06,0.000000,0.0000,0.0,0.320000,0.0,0.0
50%,1.582366e+06,0.000000,0.0000,0.0,0.640000,0.0,0.0
75%,1.712100e+06,0.000000,0.0000,0.0,1.645000,0.0,0.0
max,1.752779e+06,186.000000,190.0000,0.0,14.950000,0.0,0.0

## Preguntas Analíticas

In [13]:
#Ejercicio 13
df["rating"].mean()

np.float64(0.0)

In [14]:
#Ejercicio 14
df["duracion_min"].mean()

np.float64(21.73)

In [15]:
#Ejercicio 15
df.loc[df["duracion_min"].idxmax(), "titulo"]

'American Static'

In [16]:
#Ejercicio 16
df.sort_values(by="rating", ascending=False).head(1)

,id,titulo,fecha_estreno,genero,duracion_min,presupuesto_musd,taquilla_musd,popularidad,rating,votos,idioma_original,adulto
0,1711051,100 Years,2099-12-31,Sin género,0,0.0,0.0,0.26,0.0,0,en,False

In [17]:
#Ejercicio 17
df.sort_values(by="votos", ascending=True).head(1)

,id,titulo,fecha_estreno,genero,duracion_min,presupuesto_musd,taquilla_musd,popularidad,rating,votos,idioma_original,adulto
0,1711051,100 Years,2099-12-31,Sin género,0,0.0,0.0,0.26,0.0,0,en,False

In [18]:
#Ejercicio 18
df["genero"].value_counts()

genero
Drama              16
Terror             15
Animación          14
Sin género         12
Acción              9
Ciencia ficción     6
Crimen              6
Fantasía            5
Aventura            4
Documental          2
Comedia             2
Familia             2
Suspense            2
Misterio            2
Bélica              1
Romance             1
Historia            1
Name: count, dtype: int64

In [19]:
#Ejercicio 19
#No hay ningun encabezado que indique paises de origen.

In [20]:
#Ejercicio 20
#No hay columna con plataforma. No se puede responder a la pregunta.